apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 4 
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2        # how many pods we can add at a time
      maxUnavailable: 0 #maxUnavailable define how many pods can be unavailable during the rolling update
  selector:
    matchLabels:
       app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest  #stable-perl
        ports:
        - containerPort: 80
        
        
#in metadata names and labels for deployment
#in spec in selector matchlabels for service
#in template again metadat we have labels
#in template we have spec where we give container detail
