apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: rs01
  labels:
    app: webservice-rs
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webservice-rs
  template:
    metadata:
       labels:
         app: webservice-rs
    spec:
      containers:
        - name: httpd
          image: nginx:perl
 
 #in metadata names and labels for deployment
#in spec in selector matchlabels for service
#in template again metadat we have labels
#in template we have spec where we give container detail
