{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "tomcat.serviceAccountName" . }}
  labels:
{{ include "tomcat.labels" . | indent 4 }}
{{- end -}}
