---
apiVersion: v1
kind: Namespace
metadata:
  name: frontend
...
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: httpd-cm
  namespace: frontend
data:
  UI_ENDPOINT: service-tomcat.ui.svc.cluster.local
...
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: httpd-pod
  namespace: frontend
  labels:
    app: httpd
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: httpd
  template:
    metadata:
      labels:
        app: httpd
    spec:
      containers:
      - name: liveness
        image: sachet1994/liveness:v1
        livenessProbe:
          exec:
            command:
            - cat
            - /var/www/html/health.html
        initialDelaySeconds: 5
        periodSeconds: 5
        env:
          - name: UI_ENDPOINT
            valueFrom:
              configMapKeyRef:
                name: httpd-cm
                key: UI_ENDPOINT
...
---
apiVersion: v1
kind: Service
metadata:
  name: service-httpd
  namespace: frontend
spec:
  type: LoadBalancer
  selector:
    app: httpd
  ports:
    - protocol: TCP
      port: 80 #sserviceport
      targetPort: 80 #podport
...

